config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'races#index'

  resources :races do
    resources :events, shallow: true
  end

  resources :regions do
    resources :cities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :race
  belongs_to :event_category
end

app/models/event_category.rb
# frozen_string_literal: true

class EventCategory < ApplicationRecord
  belongs_to :event_category_group
end

app/models/event_category_group.rb
class EventCategoryGroup < ApplicationRecord
  has_many :event_categories
end

app/models/race.rb
# frozen_string_literal: true

class Race < ApplicationRecord
  has_many :events, dependent: :destroy
  validates :name, :place, :date, presence: true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_race, only: %i[new create]
  before_action :set_event, only: %i[show]

  def new
    @event = Event.new
  end

  def create; end

  def show
    @event_category = @event.event_category
    @event_category_group = @event_category.event_category_group
  end

  private

  def set_race
    @race = Race.find(params[:race_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/races_controller.rb
# frozen_string_literal: true

class RacesController < ApplicationController
  before_action :set_race, only: %i[show edit update destroy]

  def index
    @races = Race.all
  end

  def new
    @race = Race.new
  end

  def show
    @events = @race.events
  end

  def edit; end

  def create
    @race = Race.new(race_params)
    if @race.save
      redirect_to @race, notice: 'Race created'
    else
      render :new
    end
  end

  def update
    if @race.update(race_params)
      redirect_to @race, notice: 'Race updated'
    else
      render :new
    end
  end

  def destroy
    @race.destroy
    redirect_to races_path, alert: 'Race delete'
  end

  private

  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:name, :place, :date)
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def new
    @region = Region.new
  end

  def create
    # render plain: params

    @region = params[:file_upload].tempfile


    data = File.open(@region)
    widgets = DBF::Table.new(data)
      binding.pry
    
    # widgets.find(:all, GNINMB: '0200') do |widget|
    # widgets.each do |widget|
    #   binding.pry
    #   region = Region.find_by(gni_region: widget.gninmb)

    #   if region.nil?
    #     Region.create(name_region: widget.name, gni_region: widget.gninmb, socr_region: widget.socr )
    #   else
    #     City.create(name_city: widget.name, gni_city: widget.gninmb, socr_city: widget.socr, region: region )
    #   end
    # end
    

    redirect_to root_path
  end
end

# {"NAME"=>"Адыгея", "SOCR"=>"Респ", "CODE"=>"0100000000000", "INDEX"=>"", "GNINMB"=>"0100", "UNO"=>"", "OCATD"=>"79000000000", "STATUS"=>"0"}
# [11] pry(#<RegionsController>)> single.attributes[:name]

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  FLASH_TYPES_TO_CSS_CLASS = {
    notice: 'info',
    alert: 'warning',
    error: 'danger'
  }.freeze

  def class_for_flash_message(key)
    FLASH_TYPES_TO_CSS_CLASS.fetch(key.to_sym, key)
  end
end

app/views/events/show.html.erb
<h3>
  <p> Event info </p>
  <p> Title: "<%= @event.title %>" </p>
  <p> Event category: "<%= @event_category.title %>"</p>
  <p> Event category group: "<%= @event_category_group.title %>"</p>
  <p>
    <%= link_to 'Main page', root_path %>
    <%= link_to 'Back', race_path(@event.race) %>
  </p>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RaceExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-3">
      <%= render 'shared/flash_msg' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/races/_form.html.erb
<div class="form">
  <%= form_with model: @race, local: true do |form| %>

    <%= render 'shared/errors', object: @race %>

    <p>
      <%= form.label :name, class: 'form-label' %><br>
      <%= form.text_field :name, class: 'form-control'%>
    </p>

    <p>
      <%= form.label :place, class: 'form-label' %><br>
      <%= form.text_field :place, class: 'form-control' %>
    </p>

    <p>
      <%= form.label :date, class: 'form-label' %><br>
      <%= form.datetime_field :date, class: 'form-control' %>
    </p>

    <p>
      <%= form.submit class: 'btn btn-primary' %>
    </p>
  <% end %>
</div>

app/views/races/_race.html.erb
<h1> Page about "<%= race.name %>"</h1>

<h3>
  <ul>
    <li>Name: <%= race.name %></li>
    <p>Place: <%= race.place %></p>
    <p>Date: <%= race.date %></p>
    <p>Events: <% race.events.each do |event| %> </p>
      <li> <%= link_to event.title, event_path(event) %> </li>
      <% end %>


  </ul>
  <%= link_to 'Edit Race', edit_race_path(race) %> |
  <%= link_to 'Back to all Races', races_path %>
</h3>


app/views/races/edit.html.erb
<%= render 'form' %>

app/views/races/index.html.erb
<h3> <%= link_to 'Create new Race', new_race_path %> </h3>

<h3> <%= link_to 'Parse', new_region_path %> </h3>

<ul>
  <h3>
  <% @races.find_each do |race| %>
    <div class="card">
      <p> Name: <%= race.name %> </p>
      <p> Place: <%= race.place %> </p>
      <p> Date: <%= race.date %> </p>
      <p>
          <%= link_to 'Open Race', race_path(race) %> |
          <%= link_to 'Edit Race', edit_race_path(race) %> |
          <%= link_to 'Delete Race', race_path(race), data: {method: :delete, confirm: 'Are you sure?'}  %>
    </div>
    </p>
  <% end %>
  </h3>
</ul>




app/views/races/new.html.erb
<%= render 'form' %>

app/views/races/show.html.erb
<%= render @race %>

app/views/regions/new.html.erb
<%= form_with url: regions_path do |f| %>
  <label> Выберите файл для загрузки :</label>
  <%= f.file_field :file_upload %>
  <%= f.submit 'Загрузить файл', class: 'btn btn-primary mt-3' %>
<% end %>

app/views/shared/_errors.html.erb
<div>
  <% if object.errors.any?%>
    <% object.errors.full_messages.each do |msg| %>
      <div>  <%= msg %> </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flash_msg.html.erb
<main class="container mt-3">
  <div>
    <% flash.each do |key, msg| %>
      <div class="alert alert-<%= class_for_flash_message(key) %> ">
        <%= msg.html_safe %>
      </div>
    <% end %>
  </div>
</main>